name: Build a Fedora 41 minimal raw image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Image Builder Action
        uses: ondrejbudai/image-builder-action@015485277f24b67527e07d5e4addaec59cf5a76f
        with:
          distro: fedora-41
          image_type: minimal-raw

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: os-image
          path: output/fedora-41-minimal-raw-x86_64/xz/disk.raw.xz
